name: Android CI

on:
  workflow_dispatch: # allows manual triggering
  push:
    branches:
      - ci

jobs:
  build:
    runs-on: ubuntu-25.10

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false

    - name: Build llama.android c++ code
      run: ./gradlew :llama-android-core:buildCMakeDebug --no-daemon

    - name: Build llama.android library
      run: ./gradlew :llama-android-core:assembleDebug

    - name: Build sample-app
      run: ./gradlew :sample-app:assembleDebug
